### PR TITLE
Finish initial Python 3 port

### PR DESCRIPTION
**Pull request by ShadowKyogre**

### CODE REVIEW

**Comment by ShadowKyogre** [comment]
That being said, now that the print statement's fixed in the doctest, the doctest unveils this error:

```
asciidoc3: FAILED: unexpected error:
asciidoc3: ------------------------------------------------------------
Traceback (most recent call last):
  File "asciidoc3.py", line 5939, in asciidoc
    has_header = document.parse_header(doctype,backend)
  File "asciidoc3.py", line 1523, in parse_header
    self.consume_attributes_and_comments()
  File "asciidoc3.py", line 1493, in consume_attributes_and_comments
    if blocks.isnext() and 'skip' in blocks.current.options:
  File "asciidoc3.py", line 2630, in isnext
    if b.isnext():
  File "asciidoc3.py", line 3007, in isnext
    return AbstractBlock.isnext(self)
  File "asciidoc3.py", line 2471, in isnext
    reader.skip_blank_lines()
  File "asciidoc3.py", line 4376, in skip_blank_lines
    reader.read_until(r'\s*\S+')
  File "asciidoc3.py", line 4392, in read_until
    while not self.eof():
  File "asciidoc3.py", line 4341, in eof
    return self.read_next() is None
  File "asciidoc3.py", line 4345, in read_next
    result = self.read()
  File "asciidoc3.py", line 4254, in read
    result = self.read_super()
  File "asciidoc3.py", line 4248, in read_super
    result = Reader1.read(self,self.skip)
  File "asciidoc3.py", line 4106, in read
    elif self._lineno == 0 and linebytes.startswith(UTF8_BOM):
TypeError: startswith first arg must be str or a tuple of str, not bytes
**********************************************************************
File "asciidoc3.py", line 6105, in __main__.execute
Failed example:
    execute(__file__, opts, [infile])
Exception raised:
    Traceback (most recent call last):
      File "asciidoc3.py", line 5939, in asciidoc
        has_header = document.parse_header(doctype,backend)
      File "asciidoc3.py", line 1523, in parse_header
        self.consume_attributes_and_comments()
      File "asciidoc3.py", line 1493, in consume_attributes_and_comments
        if blocks.isnext() and 'skip' in blocks.current.options:
      File "asciidoc3.py", line 2630, in isnext
        if b.isnext():
      File "asciidoc3.py", line 3007, in isnext
        return AbstractBlock.isnext(self)
      File "asciidoc3.py", line 2471, in isnext
        reader.skip_blank_lines()
      File "asciidoc3.py", line 4376, in skip_blank_lines
        reader.read_until(r'\s*\S+')
      File "asciidoc3.py", line 4392, in read_until
        while not self.eof():
      File "asciidoc3.py", line 4341, in eof
        return self.read_next() is None
      File "asciidoc3.py", line 4345, in read_next
        result = self.read()
      File "asciidoc3.py", line 4254, in read
        result = self.read_super()
      File "asciidoc3.py", line 4248, in read_super
        result = Reader1.read(self,self.skip)
      File "asciidoc3.py", line 4106, in read
        elif self._lineno == 0 and linebytes.startswith(UTF8_BOM):
    TypeError: startswith first arg must be str or a tuple of str, not bytes

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.5/doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest __main__.execute[8]>", line 1, in <module>
        execute(__file__, opts, [infile])
      File "asciidoc3.py", line 6200, in execute
        asciidoc(backend, doctype, confiles, infile, outfile, options)
      File "asciidoc3.py", line 6043, in asciidoc
        sys.exit(1)
    SystemExit: 1
**********************************************************************
File "asciidoc3.py", line 6106, in __main__.execute
Failed example:
    print(outfile.getvalue())
Expected:
    <p>Hello <strong>Joe Bloggs</strong></p>
Got:
    <BLANKLINE>
**********************************************************************
1 items had failures:
   2 of  10 in __main__.execute
***Test Failed*** 2 failures.
```

Should I include a fix for the faulty encoding handling here too?

**Comment by ShadowKyogre** [comment]
I got the rest of the tests working with py3 after several edits. Going to rename the pull request and update it after I verify the changes also work with py2.

**Comment by ShadowKyogre** [comment]
This may need more initial testing with python 2.6.

I only have access to python 2.7 and 3.5.

**Comment by pepr** [comment]
@ShadowKyogre Thanks for your contribution!

**Pull request merged**
